### ISSUE TITLE
Duplicated Customers in Stripe

### ISSUE THREAD

**Issue by jhclaura** [bigcommerce/checkout-sdk-js#1029]
Hi there, we are using checkout-sdk-js with Stripe payment, and we found that, every incomplete payment will result a new Customer in Stripe, so one actual customer, who completes the payment, can have multiple Customers records in Stripe.

Is there a way to avoid the duplication? Like, if there's a way for us to pass in customer id while submitting the order, so when Big Commerce creates the payment intent, it can pass in existed customer id to avoid creating new Customer every time?

Any advice will be very helpful. Thank you.

**Comment by vmparra** [comment]
Hi @jhclaura,

In fact, we recently worked on this issue and solved most of the uses cases specially those where a customer is actually logged in. On the other side, we believed that working with guest users could be quite difficult to solve because no clear way to distinguish one from the other (i.e. shared email accounts from purchase departments used by multiple users, etc.)

Mow, having said all that we do realize there's an opportunity on payment intent reuse specially when shopper navigates back and forth before submitting payment.

Thank you for your inquiry.

**Comment by vmparra** [comment]
Closing as this issue has been addressed on PR [#2925](https://github.com/bigcommerce/bigpay/pull/2925)
