### ISSUE TITLE
Does not work for UK Address

### ISSUE THREAD

**Issue by LaudersGate** [bigcommerce/checkout-sdk-js#1090]
1. UK does not have states
2. SDK/API expects State Field as a mandatory value

Example UK Address
Terrance Morejon
72 Princes Street
ROLVENDEN LAYNE
TN17 5JT

**Comment by capsula4** [comment]
Could you provide evidence of the behaviour you are seeing? API/SDK should not expect states for the UK.

**Comment by LaudersGate** [comment]
- SDk defaults to state Lov input 
- Changing code to input and optional 
- Hide state input (since it's nit required for Uk)
-  Launch checkout. 
Payments fail. 


Or is there any evidence the SDk has been tested to and shown to work for Uk
- With state input field hidden on the ui

**Comment by LaudersGate** [comment]
UK Address format no longer includes or requires County information - this element of postal addressing was discontinued by Royal Mail in 1996 (see http://en.wikipedia.org/wiki/Postal_counties_of_the_United_Kingdom).

The names and borders of Counties have changed over and over again over the years, and only continue to exist as historical geographical interest points, and current geographical administrative areas - neither of these remaining functions of the County are likely to serve any purpose, the only reason an admin might want to include County information in the field for State/Province would be the belief that it forms part of the postal address, which it doesn't and therefore it's absence by default and the nature of the available methods by which it can be added are both non-issues.

Unless the reason for wanting to include County in the State/Province field is anything other than for correctly addressing correspondence (I suspect this would be highly unlikely), then understanding and accepting that County is not a part of a UK postal address is the simplest way of resolving this issue - just forget about Counties!

**Comment by capsula4** [comment]
Our Optimized One-Page Checkout uses the Checkout SDK behind the scenes. We have a lot merchants based in the UK that sell to a UK customer base without any problems.

Most likely the issue you are seeing are related to the way the checkout has been implemented. My advice would be to debug the JS code and see what the actual error is, rather than assuming is an issue with the UK state/province.

State/Province for the UK It's not a mandatory field, you can verify by testing our default checkout offering. The code is open source and you may check it out as a reference https://github.com/bigcommerce/checkout-js.
