### ISSUE TITLE
Add challengeRequested property to Braintree 3DSecure

### ISSUE THREAD

**Issue by twm-jamieb** [bigcommerce/checkout-sdk-js#2518]
**Is your feature request related to a problem? Please describe.**

When using Braintree the customer is being presented with a 3D Secure challenge almost every time, even though their bank may allow them to pass 3D Secure without a challenge and accept liability shift. 

**Describe the solution you'd like**

The Braintree sdk has a "challengeRequested" property when verifying a card with 3D Secure, as you can see here -https://braintree.github.io/braintree-web/current/ThreeDSecure.html#verifyCard. When set to "true" it forces a challenge if possible. Extend the challengeRequested property to the checkout-sdk so merchants can decide if they want to force a challenge.

**Additional context**
More information about challengeRequested here - https://developer.paypal.com/braintree/docs/guides/3d-secure/migration/javascript/v3/#requesting-a-cardholder-challenge

**Comment by serhii-tkachenko** [comment]
Hello @twm-jamieb 👋 

Thanks for your input.

I double checked how it works on our side and I can say that we use a bit different implementation - we trigger 3DS in cases when PayPal said us to do that. Therefore, if we add extra option to disable 3DS it might cause some issues for merchant, because customer will not be able to buy anything due to bank restriction.

In the end of the story, even if merchant has that setting disabled and card issuer/bank requires 3DS we would still ask shopper for the 3DS validation.

Let me know if it looks reasonable for you. 

P.s.: If not, we can put this feature request in our backlog for future investigation.

**Comment by twm-jamieb** [comment]
Thanks for the reply @serhii-tkachenko . This option doesn't disable 3D Secure, the payments still pass through 3D Secure, it's just that it allows the bank to process the payment through 3D Secure without presenting a challenge. 

It's an available option on the Braintree 3D Secure checkout-sdk so I think it would be worth considering.

**Comment by serhii-tkachenko** [comment]
Thanks @twm-jamieb 👍 
We will review and merge your PR as soon as possible

**Comment by serhii-tkachenko** [comment]
Close the issue, since it was resolved
