### ISSUE TITLE
Any tips making the bundle smaller?

### ISSUE THREAD

**Issue by napalm272** [bigcommerce/checkout-sdk-js#384]
When I include this library, my bundle size increased by about 500K. I'm using webpack 4 production build.  Why is this library so big when it's just a wrapper around some APIs?  Any tips on minimizing the bundle?

**Comment by davidchin** [comment]
Hi @napalm272, all assets served by us will be gzipped, therefore the actual size increase should be around 100 kb. Having said that, we do have plans to reduce the raw file size - i.e.: removing some of the larger dependencies and splitting the bundle etc... Thanks for the feedback.

**Comment by steve-ross** [comment]
Likely lodash... either switching to lodash-es and importing individual methods or using the lodash webpack optimizer would help.  

Check out how they did it in this PR for cornerstone: https://github.com/bigcommerce/cornerstone/pull/1390

**Comment by jaybeecave** [comment]
Its lodash and rxjs. The webpack analyzer included with the latest build of stencil shows how bad it is. over 4mb.

Wish we could just have a proper API instead of 

```'X-API-INTERNAL': 'This API endpoint is for internal use only and may change in the future'``` headers as a safeguard to using API endpoints

The cart process atm is so convoluted with regards to picking a shipping method and payment method.
