### ISSUE TITLE
Cancel PayPal payment method not working after selected

### ISSUE THREAD

**Issue by adaamcollins** [bigcommerce/checkout-sdk-js#549]
So, I am using the CheckoutButtonInitializer with the BraintreePayPal payment method. 

Once the user signs into their PayPal account, the page refreshes and the only payment method available is the BraintreePayPal one, which works as expected - however I can't seem to deinitalize or cancel this method in any way, to give the user choice of all payment options again - could you advise?

With Google Pay (via CheckoutButtonInitializer also), I am running the following commands if the user wants to change their mind on payment method after they've selected a card in the Google Pay modal window (and the page has refreshed after selection).

```
await checkoutService.deinitializeCustomer({
     methodId: methodId
})

await checkoutService.signOutCustomer({
     methodId: methodId
})
```
The variable `methodId` equals `googlepaystripe` or `googlepaybraintree` in the above examples.

The above works for Google Pay only. If we do the same for PayPal, it does nothing. The method is still the only one available after the actions are run.

I am assuming from [here](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/customerrequestoptions.md) that PayPal is included in the 'some' payment methods require their own sign-in/out flow - which is why I'm trying the signOutCustomer method, which seems to work for Google Pay.

**Comment by icatalina** [comment]
Hi @adaamcollins!

Due to some limitations in the way PayPal is handled, there's no way at the moment to log out after you've started the process with PayPal. 

The only available solution at the moment is redirecting the customer to the cart page and starting the checkout again by using the _Checkout_ button. All the data will still be in the checkout, but the full list of payment methods will be available.

I'll create a ticket for us to look into it, but I can't give you a timeline for it at this point.

**Comment by adaamcollins** [comment]
@icatalina thanks for the confirmation, if it's not possible we will just leave things how they are and remove the logout button for PayPal - which is in place for the other methods that do support that.

It's not a huge deal as it's an unlikely scenario for someone to logout by that point in the checkout anyway, but it'd be good to offer in future at some point!

**Comment by capsula4** [comment]
Closing as it cannot be solved due to a limitation from PayPal.
