### ISSUE TITLE
Problem using service.finalizeOrderIfNeeded(); with hosted page payment

### ISSUE THREAD

**Issue by catokx** [bigcommerce/checkout-sdk-js#604]
Good morning, i need to use some code in custom checkout sdk "after" successful payment in external payment gateway hosted page. Following the documentation https://github.com/bigcommerce/checkout-sdk-js#finalize-order i call  the await service.finalizeOrderIfNeeded(); and after this i need to call some js before redirecting to the order confirmation page. 
In most cases the redirection to the order confirmation page is done directly by the sdk, not the code in my custom checkout page, in fact in the integration panel of bigcommerce the gateway redirection page is payments.bigcommerce.com/... and cannot be changed.

Sometimes it works but i think it is only a failover behaivoir

**Comment by davidchin** [comment]
Hi @catokx, can you tell me which hosted payment method you're using?

**Comment by catokx** [comment]
Good morning David, we are using Adyen as payment gateway with
thebigcommerce integration

Il giorno ven 7 giu 2019 alle 09:02 David Chin <notifications@github.com>
ha scritto:

**Comment by davidchin** [comment]
Ah yes, for some payment methods, i.e.: Adyen, shoppers are directly redirected to the order confirmation page after a successful payment. Therefore, `finalizeOrderIfNeeded` is not necessary for these payment methods. We should probably update the documentation so it's clearer for everyone. :)

**Comment by fthobe** [comment]
Hi @davidchin , we just wasted one month of trial and error and endless emails with bigcommerce customer support. We don’t share your sense of emoji humour on this one. Will this ever be fixed or is it contemplated to implement payment forms for Adyen?

**Comment by davidchin** [comment]
Hi @fthobe, I'm really sorry to hear that. And we apologise for not able to unblock you earlier. 

As I mentioned in my last comment, for certain hosted payment methods such as Adyen, the order finalisation call is triggered directly on the server side. If the call is successful, shoppers will be redirected to the order confirmation page. As they have completed the checkout process, there's little point redirecting them to the checkout page again as their shopping cart is already converted into an order and there's nothing further for them to do. `finalizeOrderIfNeeded` method is only required for some payment methods that don't trigger the finalisation call directly on the server side. This is why I said the current documentation might not be clear enough and we should clarify the intended behaviour of various hosted payment flows we support.

Anyway, I guess this issue is related to #606. How about we continue our discussion there? It seems to me that the reason you're asking about the Adyen payment flow is that you want to trigger some GA tracking calls?

**Comment by fthobe** [comment]
Hi @davidchin, yes! We have reverted to the order confirmation page and it seems to work fine given that we can track there also the payment. BC support was very helpful on getting this up and running. If you create an empty repository with us we can fill it up with a tracking code example to implement google conversion tracking on the thank you page.
