### ISSUE TITLE
Signing out customer without checkout SDK always causes an error

### ISSUE THREAD

**Issue by LordZardeck** [bigcommerce/checkout-sdk-js#643]
Whenever i call `service.signOutCustomer()` it's making another call to load data from a cart that doesn't exist anymore (presumably because it was tied to a logged in customer).

Steps to Reproduce:

1. Add an item to your cart as a guest
2. With checkout SDK, sign in as an existing customer
3. Sign out of that customer with `service.signOutCustomer()`
4. Observe erroneous API call for non-existant cart

**Comment by icatalina** [comment]
Hi @LordZardeck!

Thanks for your question, what you describe is expected behavior.

When you sign out a customer the outcome can vary depending on your persistent cart setting.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/4542735/61917883-8dc38d80-af92-11e9-9262-7c68b5f75b88.png">

If persistent cart is `On`, the cart will be saved against that user's account and remove upon logout. Consumers of the SDK are meant to catch that specific error type and handle it appropriately (In the default checkout we redirect them to the cart page).

If persistent cart is `Off`, the cart will be anonymized and stay available for the guest user to continue with their checkout.

There's no way, other than requesting for the cart, to figure out what happened to it. Hence the request.
